packageExtensions:
  "@m-ld/m-ld@*":
    dependencies:
      sparqlalgebrajs: ^2.5.5
      sparqljs: ^3.4.1
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  jest-config@^27.0.1:
    dependencies:
      jest-runtime: ^27.0.1
  xpath-iterator@*:
    dependencies:
      node-gyp: ^7.1.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
